<%--

Copyright (c) 2012-2013, The University of Edinburgh.
All Rights Reserved

Instructor upload assessment package form

Model:

primaryRouting (action -> URL)

--%>
<%@ include file="/WEB-INF/jsp/includes/pageheader.jspf" %>
<page:page title="Upload New Assessment">

  <nav class="breadcrumbs">
    <a href="${utils:internalLink(pageContext, '/instructor/')}">QTIWorks Dashboard</a> &#xbb;
    <a href="${utils:escapeLink(primaryRouting['listAssessments'])}">Your assessments</a> &#xbb;
  </nav>
  <h2>Upload Assessment</h2>

  <div class="hints">
    <p>
      You can upload a new stored assessment item or test here. We will general
      an initial name and title for your assessment using the name of the file
      you upload and the 'title' attribute in the QTI XML.  You can
      subsequently change these details to suit.
    </p>
    <p>
      Your assessment will be validated automatically during the upload process.
      If it is not valid, or if you try it out and discover it doesn't quite work the way you want,
      then you can upload a new version of your assessment to replace it, and repeat that process
      as many times as you like.
    </p>
    <p>
      If your assessment is found to be valid, you can try it out using various "delivery settings",
      deliver your assessment to candidatates, and later access the results data generated by the
      candidates.
    </p>
  </div>

  <form:form method="post" acceptCharset="UTF-8" enctype="multipart/form-data" commandName="uploadAssessmentPackageCommand">

    <%-- Show any form validation errors discovered --%>
    <form:errors element="div" cssClass="formErrors" path="*"/>

    <fieldset>
      <div class="grid_1">
        <div class="workflowStep">1</div>
      </div>
      <div class="grid_5">
        <label for="file">Select a Content Package ZIP file or Assessment Item XML file to upload and store:</label>
        <br/>
        <form:input path="file" type="file"/>
      </div>
      <div class="grid_6">
        <aside>
          <p>
            You may upload any of the following:
          </p>
          <ul>
            <li>An IMS Content Package containing a QTI 2.1 Assessment Item plus any related resources, such as images, response processing templates...</li>
            <li>An IMS Content Package containing a QTI 2.1 Assessment Test, its Assessment Items, plus any related resources.</li>
            <li>A self-contained QTI 2.1 Assessment Item XML file.</li>
          </ul>
        </aside>
      </div>
    </fieldset>
    <div class="clear"></div>
    <fieldset>
      <div class="grid_1">
        <div class="workflowStep">2</div>
      </div>
      <div class="grid_11">
        <label for="submit">Hit "Upload New Assessment"</label>
        <br/>
        <input id="submit" name="submit" type="submit" value="Upload New Assessment"/>
      </div>
    </fieldset>

  </form:form>

</page:page>
